---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myrs
 labels:
  type: webserver
spec:
 replicas: 3
 selector:
  matchLabels:
   app: java
 template:
  metadata:
   name: mypod
   labels:
    app: java
  spec:
   containers:
    - name: myn1
      image: nginx
